EcomProj/urls.py
from django.contrib import admin
from django.urls import path,include
from core import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/',include('core.urls')),
    path('',views.homepage,name='homepage'),
    path('navbar',views.navbar,name='navbar'),
    path('login/',views.login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('logout/',views.logout,name="logout"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path('productlist/',views.productlist,name='productlist'),
    path('catprod/<slug>/',views.catprod,name='catprod'),
    path('search/',views.search,name='search'),
    path('product_detail/<slug>',views.product_detail,name='product_detail'),
    path('cart',views.cart,name='cart'),
    path('addtocart/<str:slug>', views.addtocart, name='addtocart'),
    path('decrease_quantity/<str:slug>', views.decrease_quantity, name='decrease_quantity'),
    path('clear',views.clear, name='clear'),
    path('remove_item/<slug>',views.remove_item, name='remove_item'),
    # path('checkout/', views.checkout, name='checkout'),
    # path('placeorder/', views.placeorder, name='placeorder'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    @staticmethod
    def get_all_category():
        return Category.objects.all()

class Product(models.Model):
    brand = models.CharField(max_length=100,default="Roadster")
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField()
    price = models.FloatField()
    image = models.ImageField()
    description = models.TextField()

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    @staticmethod
    def get_all_products_by_categoryslug(category_slug):
        if category_slug:
            return Product.objects.filter(category = category_slug)
        else:
            return Product.get_all_products();

class CartItem(models.Model):
    cart_id = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    quantity = models.PositiveIntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quantity} of {self.product.name}"

    def update_quantity(self, quantity):
        self.quantity = self.quantity + quantity
        self.save()

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class NewUser(UserCreationForm):
    class Meta():
        model = User
        fields = ['username','email','password1','password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
            print("already exists")
        else:
            return email

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . forms import NewUser
from django.contrib import messages,auth
from . models import Product, Category, CartItem
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
# Create your views here.
#
def navbar(request):
    category = Category.get_all_category()
    return render(request, "core/navbar.html",{'category':category})

# def checkout(request):
#     return render(request, "core/checkout.html")

def homepage(request):
    category = Category.objects.all()
    return render(request, "core/homepage.html",{'category':category})

def signup(request):
    if request.method == "POST":
        form = NewUser(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Registered Successfully!!!")
        else:
            messages.error(request, "Something went wrong!")
    else:
        form = NewUser()
    return render(request, "core/register.html",{'form':form})

def login(request):
    if request.user.is_authenticated:
        return redirect('core:homepage')
    else:
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']

            user = auth.authenticate(request, username=username, password=password)

            if user is not None:
                auth.login(request, user)
                return redirect("homepage")
        return render(request, 'core/login.html')

def logout(request):
    auth.logout(request)
    return redirect("homepage")

def productlist(request):
    category = Category.objects.all()
    product = Product.objects.all()
    return render(request, "core/productlist.html",{'product':product,'category':category})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    category = Category.objects.all()
    context = {
        'product':product,
        'category':category
    }
    return render(request, 'core/product_detail.html', context)

def catprod(request,slug):
    cat = get_object_or_404(Category, slug=slug)
    product = Product.objects.filter(category=cat)
    category = Category.objects.filter(active=True)
    context = {'category':category, 'product':product}
    return render(request, "core/catprod.html", context)

def search(request):
    q = request.GET["q"]
    product = Product.objects.filter(name__icontains=q)
    category = Category.objects.filter(active=True)
    context = {'category':category, 'product':product}
    return render(request, "core/productlist.html", context)

@login_required(login_url='login')
def cart(request):
    cart = CartItem.objects.filter(cart_id=request.user)
    context = {'cart':cart}
    return render(request, "core/cart.html",context)

@login_required(login_url='login')
def addtocart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    cart, created = CartItem.objects.get_or_create(product=product, cart_id=request.user)
    # order = Order.objects.filter(user=request.user, ordered=False)

    if CartItem.objects.filter(product=product.id).exists():
        cart.quantity += 1
        cart.save()
        return redirect('core:cart')

def decrease_quantity(request, slug):
    product = get_object_or_404(Product, slug=slug)
    cart = CartItem.objects.get(product=product, cart_id=request.user)
    if CartItem.objects.filter(product=product.id).exists():
        cart.quantity -= 1
        cart.save()
        if cart.quantity < 1:
            cart.delete()
            return redirect('core:cart')
        return redirect('core:cart')

def clear(request):
    cart = CartItem.objects.filter(cart_id=request.user)
    cart.delete()
    return redirect('core:cart')

def remove_item(request, slug):
    product = get_object_or_404(Product, slug=slug)
    ci = get_object_or_404(CartItem, product=product)
    ci.delete()
    return redirect('core:cart')

templates/core/cart.html
<!DOCTYPE html>
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!--Include the above in your HEAD tag ---------->

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>

<div class="container mb-4">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col"> </th>
                            <th scope="col">Product</th>
                            <th scope="col">Available</th>
                            <th scope="col" >Quantity</th>
                            <th scope="col" class="text-right">Price</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                      {% for ci in cart %}
                        <tr>
                            <td> <a href="{% url 'core:product_detail' ci.product.slug %}"> <img src="{{ci.product.image.url}}" /></a> </td>
                            <td> <a href="{% url 'core:product_detail' ci.product.slug %}"> {{ci.product.name}} from <h4>{{ci.product.brand}}</h4></a></td>
                            <td>In stock</td>

                            <td>
                              <a href="{% url 'core:decrease_quantity' ci.product.slug %}"><i class="fas fa-minus"></i>
                              </a>
                              {{ci.quantity}}
                              <a href="{% url 'core:addtocart' ci.product.slug %}"><i class="fas fa-plus"></i></a>
                            </td>
                            <td class="text-right">${{ci.get_total}}
                            </td>
                            <td>
                              <a href="{% url 'core:remove_item' ci.product.slug %}">
                                <i class="fas fa-times"></i>
                              </a>
                            </td>

                        </tr>
                      </tbody>
                      {% endfor %}
                     <a class="a" href="{% url 'core:clear' %}">  <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Remove All </button> </a>
                        <style media="screen">
                          .a{
                            text-decoration: none;
                            color: white;
                          }
                          .btn-sm{
                            margin-bottom: 10px;
                            margin-top: 10px;
                            padding: 10px;
                          }
                        </style>
                </table>
                <tr>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td><strong>Total</strong></td>
                  <td class="text-right"><strong>${{ci.get_all_total}}</strong></td>
                </tr>
            </div>
        </div>
        <div class="col mb-2">
            <div class="row">
                <div class="col-sm-12  col-md-6">
                   <a href="{% url 'core:productlist' %}">  <button class="btn btn-lg btn-block btn-primary">Continue Shopping</button></a>
                </div>
                <div class="col-sm-12 col-md-6 text-right">
                  <a href="#">
                    <button class="btn btn-lg btn-block btn-success text-uppercase">Checkout</button></a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/core/catprod.html
<!DOCTYPE html>
{% extends "core/navbar.html" %}
{% block body_block %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
<div class="row">
  {% for pro in product %}
    <div class="col-md-3">
        <div class="ibox">
          <a href="{% url 'core:product_detail' pro.slug %}">
            <div class="ibox-content product-box">
                <div class="img-box">
                    <img src="{{pro.imageURL}}" class="img-fluid" alt="">
                 </div>
                <div class="product-desc">
                    <span class="product-price">
                        ${{pro.price}}
                    </span>
                    <a href="{% url 'core:product_detail' pro.slug %}">
                    <small class="text-muted">{{pro.name}}</small></a>
                    <a href="{% url 'core:product_detail' pro.slug %}" class="product-name">{{pro.brand}}</a>
                    <div class="m-t text-righ">
                        <a href="{% url 'core:product_detail' pro.slug %}" class="btn btn-s btn-outline btn-primary">Info</a>
                    </div>
                </div>
            </div>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
</div>

<style media="screen">

/* E-commerce */
.product-box {
  padding: 0;
  border: 1px solid #e7eaec;
}
.product-box:hover,
.product-box.active {
  border: 1px solid transparent;
  -webkit-box-shadow: 0 3px 7px 0 #a8a8a8;
  -moz-box-shadow: 0 3px 7px 0 #a8a8a8;
  box-shadow: 0 3px 7px 0 #a8a8a8;
}
.product-imitation {
  text-align: center;
  padding: 90px 0;
  background-color: #f8f8f9;
  color: #bebec3;
  font-weight: 600;
}
.cart-product-imitation {
  text-align: center;
  padding-top: 30px;
  height: 80px;
  width: 80px;
  background-color: #f8f8f9;
}
.product-imitation.xl {
  padding: 120px 0;
}
.product-desc {
  padding: 20px;
  position: relative;
}
.ecommerce .tag-list {
  padding: 0;
}
.ecommerce .fa-star {
  color: #d1dade;
}
.ecommerce .fa-star.active {
  color: #f8ac59;
}
.ecommerce .note-editor {
  border: 1px solid #e7eaec;
}
table.shoping-cart-table {
  margin-bottom: 0;
}
table.shoping-cart-table tr td {
  border: none;
  text-align: right;
}
table.shoping-cart-table tr td.desc,
table.shoping-cart-table tr td:first-child {
  text-align: left;
}
table.shoping-cart-table tr td:last-child {
  width: 80px;
}
.product-name {
  font-size: 16px;
  font-weight: 600;
  color: #676a6c;
  display: block;
  margin: 2px 0 5px 0;
}
.product-name:hover,
.product-name:focus {
  color: #1ab394;
}
.product-price {
  font-size: 14px;
  font-weight: 600;
  color: #ffffff;
  background-color: #1ab394;
  padding: 6px 12px;
  position: absolute;
  top: -32px;
  right: 0;
}
.product-detail .ibox-content {
  padding: 30px 30px 50px 30px;
}
.image-imitation {
  background-color: #f8f8f9;
  text-align: center;
  padding: 200px 0;
}
.product-main-price small {
  font-size: 10px;
}
.product-images {
  margin: 0 20px;
}

.ibox {
  clear: both;
  margin-bottom: 25px;
  margin-top: 0;
  padding: 0;
}
.ibox.collapsed .ibox-content {
  display: none;
}
.ibox.collapsed .fa.fa-chevron-up:before {
  content: "\f078";
}
.ibox.collapsed .fa.fa-chevron-down:before {
  content: "\f077";
}
.ibox:after,
.ibox:before {
  display: table;
}
.ibox-title {
  -moz-border-bottom-colors: none;
  -moz-border-left-colors: none;
  -moz-border-right-colors: none;
  -moz-border-top-colors: none;
  background-color: #ffffff;
  border-color: #e7eaec;
  border-image: none;
  border-style: solid solid none;
  border-width: 3px 0 0;
  color: inherit;
  margin-bottom: 0;
  padding: 14px 15px 7px;
  min-height: 48px;
}
.ibox-content {
  margin-top: 10px;
  background-color: #ffffff;
  color: inherit;
  padding: 15px 20px 20px 20px;
  border-color: #e7eaec;
  border-image: none;
  border-style: solid solid none;
  border-width: 1px 0;
}
.ibox-footer {
  color: inherit;
  border-top: 1px solid #e7eaec;
  font-size: 90%;
  background: #ffffff;
  padding: 10px 15px;
}
</style>

{% endblock %}

templates/core/login.html
<!DOCTYPE html>
<title>Login</title>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Login</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
	color: #fff;
	background: #3598dc;
}
.form-control {
	min-height: 41px;
	background: #f2f2f2;
	box-shadow: none !important;
	border: transparent;
}
.form-control:focus {
	background: #e2e2e2;
}
.form-control, .btn {
	border-radius: 2px;
}
.login-form {
	width: 350px;
	margin: 30px auto;
	text-align: center;
}
.login-form h2 {
	margin: 10px 0 25px;
}
.login-form form {
	color: #7a7a7a;
	border-radius: 3px;
	margin-bottom: 15px;
	background: #fff;
	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
	padding: 30px;
}
.login-form .btn {
	font-size: 16px;
	font-weight: bold;
	background: #3598dc;
	border: none;
	outline: none !important;
}
.login-form .btn:hover, .login-form .btn:focus {
	background: #2389cd;
}
.login-form a {
	color: #fff;
	text-decoration: underline;
}
.login-form a:hover {
	text-decoration: none;
}
.login-form form a {
	color: #7a7a7a;
	text-decoration: none;
}
.login-form form a:hover {
	text-decoration: underline;
}
</style>
</head>
<body>
<div class="login-form">
    <form method="post">{% csrf_token %}
        <h2 class="text-center">Login</h2>
        <div class="form-group has-error">
        	<input type="text" class="form-control" name="username" placeholder="Username" required="required">
        </div>
		<div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="Password" required="required">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg btn-block">Log in</button>
        </div>
        <p><a href="#">Lost your Password?</a></p>
    </form>
    <p class="text-center small">Don't have an account? <a href="{% url 'signup' %}">Sign up here!</a></p>
</div>
</body>
</html>

templates/core/newfile.html
{% extends "core/navbar.html" %}
{% block body_block %}
{% endblock %}

templates/core/product_detail.html
<!DOCTYPE html>
{% extends "core/navbar.html" %}
{% block body_block %}
{% load static %}
<html>
<head>
<title>UI Design</title>
<!-- <meta name="viewport" content="width=device-width, initial-scale=1.0">

<meta charset=-"utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
  <link rel="stylesheet" href="style.css"> -->
</head>
<body>
<div class="outer">
  <div class="center-wrapper">
    <div class="container-fluid content">
      <div class="row">
        <div class="col-12 col-sm-12 col-md-6 shoe-slider">
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <img src="{{ product.image.url }}" alt="">
          </div>
        </div>
        <div class="col-12 col-sm-12 col-md-6 shoe-content">
          <div class="text1">
            <span>{{product.category}}</span>
            <span>{{product.name}}</span>
          </div>
          <div class="text2">
            ${{product.price}}
          </div>
          <div class="text3">
            {{product.brand}}
          </div>
          <div class="text4">
            DESCRIPTION
          </div>
          <div class="text5">
          {{product.description}}
          </div>
          <div class="btn-wrapper">
            <a href="{% url 'core:addtocart' product.slug %}" style="outline:none;">
            <button type="submit" class="btn">Add to Cart</button></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script> -->
</body>


<style media="screen">
@import url('https://fonts.googleapis.com/css?family=Montserrat:400,400i,500,500i,600,600i,700,700i&display=swap');

*{
margin:0px;
padding:0px;
box-sizing:border-box;
font-family: 'Montserrat', sans-serif;
}
.outer{
width:100%;
height:100vh;
margin: auto;
position: relative;
background-color: #03849d05;
}
.center-wrapper{
position: absolute;
width:70%;
height: 70vh;
min-height:500px;
background: #fff;
top:50%;
left:50%;
transform: translate(-50% , -50%);
box-shadow: 0px 2px 10px rgba(0,0,0,.12);
border-radius:15px;
display: flex;
justify-content: center;
align-items: center;
padding: 0px;
}
.content{
width:90%;
border-radius:4px;
}
.shoe-slider{
background: #03849d05;
height: 100%;
}
.shoe-content{
background: #fff;
position: relative;
}
.text1{
width:100%;
height: auto;
border-left:1px solid #333333;
padding-left: 10px;
}
.text1 span{
display: block;
}
.text1 span:nth-child(1){
color:#03849D;
font-size:13px;
}
.text1 span:nth-child(2){
color:#6b6b6b;
font-size: 13px;
}
.text2 {
  font-size: 30px;
  color: #444;
  padding-top: 10px;
  padding-bottom: 5px;
}
.text3 {
  font-size: 16px;
  color: #444;
  padding-top: 10px;
  padding-bottom: 10px;
  font-weight: 500;
  letter-spacing: 2px;
}
.text4 {
  font-size: 12px;
  color: #6b6b6b;
  padding-top: 10px;
  padding-bottom: 10px;
}
.text5 {
  font-size: 12px;
  color: #6b6b6b;
  padding-top: 10px;
  padding-bottom: 10px;
  line-height: 23px;
}
.btn-wrapper{
  width: 100%;
  height: auto;
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 10px;
}
.btn-wrapper .btn{
  box-shadow: 2px 5px 20px rgba(32,57,90,0.479);
  background: #03849D;
  border-radius: 32px;
  color: #fbfbfb;
  font-size: 14px;
  padding: 8px 48px;
  border: none;
  outline: none;
}

.btn-wrapper, .btn:focus, [type="submit"]:focus {
   outline: none;
}
.qantity .fas{
color:#dbdbdb;
font-size: 9px;
}
.one{
padding-left: 14px;
padding-right: 14px;
}
.social-icons{
position: absolute;
top:50%;
right:-70px;
transform: translateY(-50%);
}
.social-icons i{
display: block;
}
.social-icons .fa-twitter{
background: #4099FF;
width: 30px;
height:30px;
line-height: 30px;
text-align: center;
color:#fff;
border-radius: 50%;
font-size: 12px;
box-shadow: 2px 5px 20px rgba(32,57,90,0.479);
}
.social-icons .fa-pinterest-p{
background: #C92228;
width: 30px;
height:30px;
line-height: 30px;
text-align: center;
color:#fff;
margin-top: 15px;
margin-bottom: 15px;
border-radius: 50%;
font-size: 12px;
box-shadow: 2px 5px 20px rgba(32,57,90,0.479);
}
.social-icons .fa-facebook-f{
background: #3B5998;
width: 30px;
height:30px;
line-height: 30px;
text-align: center;
color:#fff;
border-radius: 50%;
font-size: 12px;
box-shadow: 2px 5px 20px rgba(32,57,90,0.479);
}
.carousel .carousel-indicators{
bottom: -40px;
}
.carousel .carousel-indicators li{
width:60px;
height:60px;
border-radius: 50%;
border:none;
display: flex;
justify-content: center;
align-items: center;
}
.carousel .carousel-indicators li img{
max-width: 80%;
height: auto;
vertical-align: middle;
border-radius: 50%;
}
.carousel .carousel-indicators li.active{
background: #fff;
box-shadow: 2px 5px 20px rgba(32,57,90,0.379);
}
.carousel .carousel-indicators li:nth-child(2){
margin-left: 50px;
margin-right: 50px;
}
.carousel-control-next,
.carousel-control-prev{
position: absolute;
width:50px;
height:50px;
top:92%;
z-index: 999999;
}
.carousel-control-prev-icon,
.carousel-control-next-icon{
background-image: none;
width:10px;
height: 10px;
transform: rotate(45deg);
}
.carousel-control-prev-icon{
border-left:2px solid black;
border-bottom:2px solid black;
}
.carousel-control-next-icon{
border-top:2px solid black;
border-right:2px solid black;
}
.carousel-control-prev{
left:33%;
}
.carousel-control-next{
right:33%;
}
span.qantity {
  text-align: center;
}
.quantity-text {
  color: #dbdbdb;
  font-size: 9px;
  margin-top: 4px;
}
@media only screen and (min-width:768px) and (max-width: 1024px) {
.center-wrapper{
  height:auto;
}
.social-icons{
  right:-55px;
}
}
@media only screen and (max-width: 767px) {
.outer{
  height:auto;
}
.shoe-content{
  margin-top: 55px;
}
.center-wrapper{
  height: auto;
  margin: 20px;
  border-radius: 0px;
  width: 90%;
  padding-bottom: 20px;
  top:unset;
  left:unset;
  transform:unset;
  -webkit-transform:unset;
  -moz-transform:unset;
  -ms-transform:unset;
  -o-transform:unset;
  box-shadow: 0px 2px 10px rgba(0,0,0,.10);
}
.content{
  width:100%;
}
.social-icons {
  position: absolute;
  top: 14%;
  right: -12px;
}
.carousel .carousel-indicators li{
  width:120px;
  height:35px;
}
.carousel-control-next, .carousel-control-prev{
  top:82%;
}
.carousel-control-prev{
  left:27%;
}
.carousel-control-next{
  right:27%;
}
.carousel .carousel-indicators{
  bottom:-4px;
}
.text2{
  font-size:22px;
}
.text3{
  font-size:14px;
}

}


</style>
</html>
{% endblock %}